dbt_python_script:
  outputs:
    dev:
      account: tn60754.ap-northeast-1.aws
      database: AIRBYTE_DATABASE
      password: password
      role: AIRBYTE_ROLE
      schema: AIRBYTE_SCHEMA
      threads: 1
      type: snowflake
      user: AIRBYTE_USER
      warehouse: AIRBYTE_WAREHOUSE
  target: dev
